# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: GetPetsy FTP-Deploy
on:
  push:
    branches: ["main"]
jobs:
  web-deploy:
    name: 🎉 Deploy On GetPetsy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: junaid.transcendedu.net
          username: albazar@junaid.transcendedu.net
          password: ywNvgd2DQvkL
          timeout: 9999999
